<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>OWCraft</AssemblyName>
    <RootNamespace>OWCraft</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Outer Wilds</GameDir>
    <Managed>$(GameDir)\OuterWilds_Data\Managed</Managed>
    <ModsDir Condition="'$(ModsDir)' == ''">$(AppData)\OuterWildsModManager\OWML\Mods\Yaekai.OWCraft</ModsDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OWML" Version="2.16.3" IncludeAssets="compile" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="$(Managed)\Assembly-CSharp.dll" Private="false" Publicize="false" />
    <Reference Include="$(Managed)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.PhysicsModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="$(Managed)\Unity.InputSystem.dll" Private="false" />
    <Reference Include="$(Managed)\System.IO.Compression.dll" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <None Include="manifest.json;default-config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="CopyToMods" AfterTargets="Build" Condition="Exists('$(AppData)\OuterWildsModManager\OWML')">
    <ItemGroup><ModFiles Include="$(OutDir)OWCraft.dll;$(OutDir)manifest.json;$(OutDir)default-config.json" /></ItemGroup>
    <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(ModsDir)" />
  </Target>
</Project>
